SCREEN_WIDTH = 480
SCREEN_HEIGHT = 720
FPS = 60

PLAYER_LIVES = 3
PLAYER_CONTINUES = 2
PLAYER_SPEED = 300
PLAYER_INVULNERABILITY_SECONDS = 2.0
PLAYER_SHIELD_INVULNERABILITY_SECONDS = 0.8
PLAYER_HITBOX_SIZE = (10, 10)
PLAYER_HITBOX_OFFSET = (0, 0)
PLAYER_WEAPON_LEVEL_LOSS_ON_HIT = 1
PLAYER_MAX_SHIELD = 10
PLAYER_STARTING_SHIELD = 5
PLAYER_SHIELD_HIT_DAMAGE = 1
PLAYER_SHIELD_RECHARGE_ENABLED = False
PLAYER_SHIELD_FLASH_SECONDS = 0.35
SHIELD_PICKUP_VALUE = 5
SHIELD_PICKUP_BONUS_SCORE = 250
SHIELD_HIT_MESSAGE_DURATION_SECONDS = 1.0

MAX_WEAPON_LEVEL = 4
MAX_BOMBS = 3
BOMB_COOLDOWN_SECONDS = 5.0
BOMB_DAMAGE = 100
BOSS_TEST_SECRET_SEQUENCE = ("UP", "UP", "DOWN", "DOWN", "UP")

BOSS_HP = 1000
BOSS_SCORE = 3000
BOSS_SPAWN_TIME_SECONDS = 124.0
STAGE_DURATION_SECONDS = 130.0
CHECKPOINT_TIMES_SECONDS = (0.0, 45.0, 62.0, BOSS_SPAWN_TIME_SECONDS)
CHECKPOINT_RECOVERY_MINIMUMS = {
    CHECKPOINT_TIMES_SECONDS[1]: {"weapon_level": 2, "bomb_count": 1},
    CHECKPOINT_TIMES_SECONDS[2]: {"weapon_level": 3, "bomb_count": 1},
    CHECKPOINT_TIMES_SECONDS[3]: {"weapon_level": 4, "bomb_count": 2},
}
ENEMY_DENSITY_TARGETS = {
    "early": (3, 5),
    "mid": (5, 8),
    "late": (7, 10),
}

WEAPON_DAMAGE_BY_LEVEL = {
    1: 2,
    2: 4,
    3: 8,
    4: 16,
}

WEAPON_COOLDOWN_BY_LEVEL = {
    1: 0.25,
    2: 0.22,
    3: 0.20,
    4: 0.16,
}

COIN_SCORE = 25
MAXED_PICKUP_SCORE = 250
BACKGROUND_SCROLL_SPEED = 75
COIN_DROP_CHANCE = 0.80
PLAYER_BOMB_EFFECT_FRAME_TIME = 0.08
BOSS_DEFEAT_EFFECT_FRAME_TIME = 0.09

VICTORY_CONGRATULATIONS_SECONDS = 8.0
OPENING_STORY_SCROLL_SPEED = 36.0
OPENING_STORY_SCROLL_START_Y = 600
OPENING_STORY_LINE_HEIGHT = 40
OPENING_STORY_AUTO_START_Y = SCREEN_HEIGHT // 2
CREDITS_SCROLL_SPEED = 34.0
CREDITS_SCROLL_START_Y = 650
CREDITS_LINE_HEIGHT = 31

ENEMY_FRAME_SIZES = {
    "SCOUT": (54, 54),
    "ZIGZAG": (60, 58),
    "HEAVY": (76, 68),
    "SHOOTER": (66, 64),
}

ENEMY_STATS = {
    "SCOUT": {
        "hp": 4,
        "score": 100,
        "vertical_speed": 145,
        "shoot_interval": 1.8,
        "bullet_speed": 190,
        "horizontal_track_speed": 52,
        "max_horizontal_speed": 80,
    },
    "ZIGZAG": {
        "hp": 8,
        "score": 200,
        "vertical_speed": 125,
        "shoot_interval": 1.6,
        "bullet_speed": 205,
        "horizontal_track_speed": 38,
        "max_horizontal_speed": 130,
        "wave_amplitude": 90,
        "wave_frequency": 2.8,
    },
    "SHOOTER": {
        "hp": 10,
        "score": 300,
        "vertical_speed": 88,
        "shoot_interval": 1.15,
        "bullet_speed": 235,
        "horizontal_track_speed": 68,
        "max_horizontal_speed": 105,
        "target_y": 165,
        "hover_duration": 6.0,
    },
    "HEAVY": {
        "hp": 20,
        "score": 400,
        "vertical_speed": 72,
        "shoot_interval": 2.1,
        "bullet_speed": 180,
        "horizontal_track_speed": 34,
        "max_horizontal_speed": 55,
    },
}

ENEMY_ATTACK_FLASH_SECONDS = 0.22
ENEMY_ATTACK_FRAME_LEAD_SECONDS = 0.25
ENEMY_BANK_SPEED_THRESHOLD = 18
ENEMY_INITIAL_SHOOT_TIMER_FACTOR = 0.65
ENEMY_DESPAWN_MARGIN = 30
ENEMY_TRACKING_RESPONSE = 0.9
ENEMY_ZIGZAG_TRACKING_MULTIPLIER = 0.45
ENEMY_HOVER_VERTICAL_SPEED = 18
ENEMY_EXIT_VERTICAL_SPEED = 115
ENEMY_PROJECTILE_Y_OFFSET = 4
ENEMY_DEFAULT_AIM_DIRECTION = (0, 1)
ENEMY_ZIGZAG_DOWNWARD_SPREAD_ANGLES = [-18, 18]
ENEMY_ZIGZAG_AIMED_SPREAD_ANGLES = [-12, 0, 12]
ENEMY_SHOOTER_FAN_INTERVAL = 3
ENEMY_SHOOTER_FAN_ANGLES = [-14, 0, 14]
ENEMY_HEAVY_SIDE_VOLLEY_INTERVAL = 2
ENEMY_HEAVY_SIDE_ANGLES = [-18, 18]
ENEMY_HEAVY_SIDE_SPEED_MULTIPLIER = 0.9

BOSS_SCALE = 1.6
BOSS_SPRITESHEET_COLUMNS = 3
BOSS_SPRITESHEET_ROWS = 2
BOSS_SPRITESHEET_FRAME_COUNT = 6
BOSS_BASE_FRAME_SIZE = (160, 140)
BOSS_FRAME_IDLE = 0
BOSS_FRAME_BANK_LEFT = 1
BOSS_FRAME_BANK_RIGHT = 2
BOSS_FRAME_CHARGE = 3
BOSS_FRAME_ATTACK = 4
BOSS_PROJECTILE_DAMAGE = 1
BOSS_SWEEP_Y = 138
BOSS_CENTER_Y = 118
BOSS_RADIAL_INTERVAL_SECONDS = 5.0
BOSS_RADIAL_CHARGE_SECONDS = 0.5
MAX_BOSS_BULLETS = 180
BOSS_SWEEP_SPEED = 96.0
BOSS_ENTER_SPEED = 76.0
BOSS_CENTER_MOVE_SPEED = 180.0
BOSS_RETURN_MOVE_SPEED = 140.0
BOSS_INITIAL_VOLLEY_TIMER = 0.25
BOSS_SWEEP_RESUME_VOLLEY_TIMER = 0.15
BOSS_CENTER_REACHED_DISTANCE = 6
BOSS_RETURN_REACHED_DISTANCE = 4
BOSS_TARGET_EPSILON_DISTANCE = 1
BOSS_SWEEP_SIDE_MARGIN = 90
BOSS_SWEEP_EDGE_PADDING = 8
BOSS_SWEEP_BOB_FREQUENCY = 1.8
BOSS_SWEEP_BOB_AMPLITUDE = 7
BOSS_VISUAL_BANK_SPEED_THRESHOLD = 12
BOSS_PROJECTILE_Y_OFFSET = 8
BOSS_SWEEP_VOLLEY_INTERVAL = 0.22
BOSS_SWEEP_BULLET_SPEED = 190
BOSS_SWEEP_BULLET_LIFETIME = 5.0
BOSS_SWEEP_FAN_BULLET_COUNT = 5
BOSS_SWEEP_FAN_ANGLE_START = 60
BOSS_SWEEP_FAN_ANGLE_END = 120
BOSS_LANE_PATTERN_INTERVAL = 4
BOSS_SWEEP_LANES = [60, 120, 180, 240, 300, 360, 420]
BOSS_SWEEP_ATTACK_FLASH_SECONDS = 0.18
BOSS_RADIAL_ATTACK_FLASH_SECONDS = 0.35
BOSS_RADIAL_BULLET_COUNT = 28
BOSS_RADIAL_BULLET_SPEED = 150
BOSS_RADIAL_BULLET_LIFETIME = 2.3

BOSS_CHARGE_GLOW_SIZE = (240, 240)
BOSS_CHARGE_GLOW_CENTER = (120, 120)
BOSS_CHARGE_OUTER_GLOW_COLOR = (255, 70, 70, 55)
BOSS_CHARGE_INNER_GLOW_COLOR = (255, 210, 120, 65)
BOSS_CHARGE_OUTER_GLOW_RADIUS = 116
BOSS_CHARGE_INNER_GLOW_RADIUS = 78
BOSS_CHARGE_OUTER_GLOW_WIDTH = 8
BOSS_CHARGE_INNER_GLOW_WIDTH = 4

PLAYER_PROJECTILE_FRAME_SIZE = (20, 36)
PLAYER_SHIELD_FRAME_COLUMNS = 6
PLAYER_SHIELD_FRAME_ROWS = 1
PLAYER_SHIELD_FRAME_COUNT = 6
PLAYER_SHIELD_WIDTH_SCALE = 1.35
PLAYER_SHIELD_HEIGHT_SCALE = 1.25
PLAYER_SHIELD_FRAME_TIME = 0.08
PLAYER_SHIELD_ALPHA = 115
PLAYER_SHIELD_FLASH_ALPHA = 210
ENEMY_PROJECTILE_FRAME_SIZE = (18, 28)
HEAVY_PROJECTILE_SIZE = (30, 30)
BOSS_ORB_PROJECTILE_SIZE = (48, 48)
PROJECTILE_BOUNDS_MARGIN = 30
